services:
  mariadb:
    build:
      dockerfile: Dockerfile
      context: ./mariadb/
    env_file: .env
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASS
      - MYSQL_ROOT_PASSWORD
    ports:
      - "3307:3306"
    volumes:
      - mariadb:/var/lib/mysql

  wordpress:
    build:
      dockerfile: Dockerfile
      context: ./wordpress/
    env_file: .env
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    volumes:
      - wordpress:/var/www/html

  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx/
    env_file: .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html:ro

volumes:
  mariadb: {}
  wordpress: {}