services:
  mariadb:
    build:
      dockerfile: dockerfile
      context: ./mariadb/
    env_file: .env
    environment: #to state vars being used, optional
      - DB_NAME
      - DB_USER
      - DB_PASS
      - MYSQL_ROOT_PASSWORD
    ports:
      - "3306:3306" #to test db from host
  # nginx:
  #    build:
  #     dockerfile: dockerfile
  #     context: ./nginx/
  #     #ports
  # wordpress:
  #     build:
  #     dockerfile: dockerfile
  #     context: ./wordpress/


  # exposing ports so you can access them from host system?




# # video
#   depends_on:
#     service_name:
#       condition: service_healthy

# healthcheck:
#   test: ["ping command"] 
#   interval: 5s
#   timeout: 2s
#   retries: 5
# depends_on:
#   service_name:
#     condition: service_started