services:
  mariadb:
    build:
      dockerfile: dockerfile
      context: ./mariadb/
      # ports
    environment:
      - TEST=value
  nginx:
     build:
      dockerfile: dockerfile
      context: ./nginx/
      #ports
  wordpress:
      build:
      dockerfile: dockerfile
      context: ./wordpress/


  # exposing ports so you can access them from host system?




# video
  depends_on:
    service_name:
      condition: service_healthy

healthcheck:
  test: ["ping command"] 
  interval: 5s
  timeout: 2s
  retries: 5
depends_on:
  service_name:
    condition: service_started