services:
  mariadb:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./mariadb/
    env_file: .env
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASS
      - MYSQL_ROOT_PASSWORD
    ports:
      - "3307:3306"
    volumes:
      - mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  wordpress:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./wordpress/
    env_file: .env
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    volumes:
      - wordpress:/var/www/html
    environment:
      WORDPRESS_DEBUG: "true"
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', true);

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx/
    env_file: .env
    depends_on:
      mariadb:
        condition: service_healthy
      wordpress:
          condition: service_healthy
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html:ro

volumes:
  mariadb: {}
  wordpress: {}