# Define the services (containers)
services:
  # MariaDB Database Service
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always
    healthcheck:
      # This check ensures the database is fully initialized and ready for connections.
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

 # WordPress Service
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file: .env
    volumes:
      # The wordpress files are mounted here. Nginx will also use this volume.
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always
    depends_on:
      mariadb:
        # This is CRITICAL: it tells WordPress to wait until MariaDB is healthy.
        condition: service_healthy
    # extra_hosts:  #suggested by chat cuz host machine /etc/host doesnt always get inherited
    #   - "mywordpress.local:127.0.0.1"

  # Nginx Web Server Service
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    env_file: .env
    ports:
      # Maps port 443 on your computer to port 443 in the container.
      - "443:443"
    volumes:
      # Nginx needs access to the WordPress files to serve them.
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always
    depends_on:
      - wordpress

# Define the volumes for persistent data storage
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ~/data/mariadb # Creates a folder in your home directory
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: ~/data/wordpress # Creates a folder in your home directory
      o: bind

# Define the custom network for inter-container communication
networks:
  inception:
    driver: bridge